version: 2
updates:
  # Front React - Thread
  - package-ecosystem: "npm"
    directory: "/thread"
    schedule:
      interval: "daily"
    target-branch: "develop"

  # Front React - Sender
  - package-ecosystem: "npm"
    directory: "/sender"
    schedule:
      interval: "daily"
    target-branch: "develop"

  # API NestJS
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "daily"
    target-branch: "develop"

  # Terraform
  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "daily"
    target-branch: "develop"
