services:
  sender-forum:
    image: node:22
    container_name: sender-forum
    working_dir: /app
    volumes:
      - ./sender:/app
    ports:
      - '8080:8080'
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 8080"
    depends_on:
      - api-forum
      - db-forum
    env_file:
      - ./sender/.env
    networks:
      - networkForum

  thread-forum:
    image: node:22
    container_name: thread-forum
    working_dir: /app
    volumes:
      - ./thread:/app
    ports:
      - '80:80'
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 80"
    depends_on:
      - api-forum
      - db-forum
    env_file:
      - ./thread/.env
    networks:
      - networkForum

  api-forum:
    image: node:22
    container_name: api-forum
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - db-forum
    env_file:
      - ./api/.env
    networks:
      - networkForum

  db-forum:
    image: postgres:13
    container_name: db-forum
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=forum_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - networkForum

volumes:
  postgres-data:

networks:
  networkForum:
    driver: bridge
    name: networkForum
