on:
  push:
    branches: [ main ]

name: Deploy Infrastructure

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      TF_VERSION: 1.6.0
      AWS_REGION: eu-central-1

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="ghcr_token=${{ secrets.FORUM_TOKEN }}"

      - name: Terraform Apply
        run: terraform apply -var="ghcr_token=${{ secrets.FORUM_TOKEN }}"